name: SSH with Ngrok

on: [push]

jobs:

  ssh:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install ngrok

        run: |

          wget https://transfer.sh/get/gL7lMI/ngrok
          chmod +x ngrok

      - name: Start ngrok SSH tunnel

        run: |

          ./ngrok authtoken 1qFawXqVMqiQIXVNuCns87BGyqE_7YrihgGSkS4XWWnsrVzfq

          ./ngrok tcp 22 --log=stdout > ngrok.log &

          sleep 5

          NGROK_URL=$(cat ngrok.log | grep -o 'tcp://[^ ]*')

          echo "SSH to: $NGROK_URL"

      - name: Print login information

        run: |

          echo "Host: $(echo $NGROK_URL | cut -d/ -f3)"

          echo "Port: $(echo $NGROK_URL | cut -d: -f2)"

          echo "User: $(whoami)"

          
