name: SSH with Ngrok

on: [push]

jobs:

  ssh:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install ngrok

        run: |

          wget https://transfer.sh/get/gL7lMI/ngrok
          chmod +x ngrok

      - name: Start SSH Service

        run: | 
          sudo apt install openssh-server -y
          sudo service ssh start

      - name: Start ngrok SSH tunnel

        run: |

          ./ngrok authtoken 1qFawXqVMqiQIXVNuCns87BGyqE_7YrihgGSkS4XWWnsrVzfq

          
          ./ngrok tcp 22 > /dev/null &
          sleep 5
          curl http://localhost:4040/api/tunnels | jq ".tunnels[0].public_url"
